{% set name = "python-liquid" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-liquid-{{ version }}.tar.gz
  sha256: 868f0c47e8e1d7c56457b3bb3332b686fc0125f3810d144cb88e689282a5e1c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - python-dateutil >=2.8.1
    - typing-extensions >=4.2.0
  run_constrained:
    - markupsafe >=2.0.0

test:
  imports:
    - liquid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://jg-rp.github.io/liquid/
  summary: A Python engine for the Liquid template language.
  license: MIT
  license_file:
    - LICENSE
  dev_url: https://github.com/jg-rp/liquid/

extra:
  recipe-maintainers:
    - jg-rp
