{% set name = "python-liquid" %}
{% set version = "1.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 70019fe2b14b698d5445ba43e598aade18390db088aa1ec959644d40f26a3da6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.14
  run:
    - python >=3.7
    - python-dateutil >=2.8.1
    - typing-extensions >=4.2.0
  run_constrained:
    - markupsafe >=2.0.0

test:
  imports:
    - liquid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://jg-rp.github.io/liquid/
  summary: A Python engine for the Liquid template language.
  license: MIT
  license_file:
    - LICENSE
  dev_url: https://github.com/jg-rp/liquid/

extra:
  recipe-maintainers:
    - jg-rp
