{% set name = "python-liquid" %}
{% set version = "1.12.2" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 46b5deb2337c1afe91760f2da46b05f17b55482023da441a4a78d096c4271d19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.14
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.8.1
    - typing-extensions >=4.2.0
    - importlib-resources >=5.10.0
  run_constrained:
    - markupsafe >=2.0.0,<3

test:
  imports:
    - liquid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://jg-rp.github.io/liquid/
  summary: A Python engine for the Liquid template language.
  license: MIT
  license_file:
    - LICENSE
  dev_url: https://github.com/jg-rp/liquid/

extra:
  recipe-maintainers:
    - jg-rp
